# Generated by Django 4.0.4 on 2022-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.CharField(default='', max_length=100),
        ),
    ]
